# Generated by Django 5.0.6 on 2024-06-20 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_created_at_alter_product_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="VersionProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_version",
                    models.SmallIntegerField(default=0, verbose_name="Версия продукта"),
                ),
                (
                    "name_version",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Название версии",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Версия активна"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия продукта",
                "verbose_name_plural": "Версии продуктов",
                "ordering": ("number_version",),
            },
        ),
    ]
