# Generated by Django 4.2.2 on 2024-07-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("id",),
                "permissions": [
                    ("is_published", "Подтверждает публикацию"),
                    ("is_description", "Может менять описание"),
                    ("is_category", "Может менять категорию"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="publisher",
            field=models.BooleanField(default=False, verbose_name="Опубликовать"),
        ),
    ]
